run:
	python manage.py runserver

migration:
	python manage.py makemigrations

migrate:
	python manage.py migrate

superuser:
	python manage.py createsuperuser

shell:
	python manage.py shell

test:
	python manage.py test

del_requirements:
	rm -rf requirements.txt

freeze: del_requirements
	pip freeze > requirements.txt
