# Generated by Django 5.0.9 on 2024-11-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='typ',
            field=models.CharField(choices=[('WANTED', 'Wanted'), ('EVENT', 'Event'), ('RENTAL', 'Rental'), ('SALE', 'Sale'), ('CONVERSATION', 'Conversation')], default='SALE', max_length=20),
        ),
    ]
